[env:esp32-s3-devkitc-1]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
    platformio/tool-esptoolpy@1.40801.0
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -Wall
    -Wextra
