[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
  bblanchon/ArduinoJson@^7.4.2
build_flags =
  -D PAN_PIN=17
  -D TILT_PIN=18
  -D PAN_MIN_DEG=30
  -D PAN_MAX_DEG=150
  -D TILT_MIN_DEG=45
  -D TILT_MAX_DEG=135
  -D COMMAND_TIMEOUT_MS=500
